// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Account struct {
	ID        int64     `json:"id"`
	Owner     string    `json:"owner"`
	Balance   int64     `json:"balance"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"createdAt"`
}

type Entry struct {
	ID        int64 `json:"id"`
	AccoundID int64 `json:"accoundID"`
	// can be -ve or +ve
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"createdAt"`
}

type Transfer struct {
	ID            int64 `json:"id"`
	FromAccoundID int64 `json:"fromAccoundID"`
	ToAccoundID   int64 `json:"toAccoundID"`
	// must only be +ve
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"createdAt"`
}
